# Generated by Django 4.2 on 2025-05-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('health', 'สายสุขภาพ'), ('engineering', 'สายวิศวกรรม'), ('architecture', 'สายสถาปัตยกรรม'), ('language', 'สายภาษา'), ('volunteer', 'ค่ายจิตอาสา'), ('digital-it', 'ดิจิตอล ไอที')], max_length=20)),
                ('participants', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('fee', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='camp_images/')),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('camp_start_date', models.DateField(blank=True, null=True)),
                ('camp_end_date', models.DateField(blank=True, null=True)),
                ('organizer', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('online', 'ออนไลน์'), ('onsite', 'ออนไซต์')], max_length=10)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
