# Generated by Django 4.2 on 2025-05-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0003_studentprofile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='google_profile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
