# Generated by Django 4.2 on 2025-05-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0004_studentprofile_google_profile_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='google_profile_url',
        ),
    ]
