# Generated by Django 4.2 on 2025-05-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0005_remove_studentprofile_google_profile_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_picture',
        ),
    ]
